#!/usr/bin/env bash
# Pick BGM track from PR/content signals; write workspace + Remotion selection file.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
  echo "Not in a git repo" >&2
  exit 1
}
cd "$ROOT"

SKILL_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORKSPACE="${ROOT}/docs/codestory/.workspace"
CONTEXT="${WORKSPACE}/pr-context.json"
BRIEF="${WORKSPACE}/change-brief.md"
OUT_JSON="${WORKSPACE}/audio-choice.json"
REMOTION_SRC="${ROOT}/docs/codestory/remotion/src"
SELECTION_TS="${REMOTION_SRC}/bgmSelection.ts"

mkdir -p "$WORKSPACE" "$REMOTION_SRC"

python3 - <<'PY' "$CONTEXT" "$BRIEF" "$OUT_JSON" "$SELECTION_TS"
import json, re, sys
from pathlib import Path

context_path, brief_path, out_json, selection_ts = map(Path, sys.argv[1:5])

text_parts = []
if context_path.exists():
    ctx = json.loads(context_path.read_text())
    text_parts.extend([
        ctx.get("title", ""),
        ctx.get("body", ""),
        ctx.get("diff_summary", ""),
        json.dumps(ctx.get("files", [])),
        str(ctx.get("additions", 0)),
        str(ctx.get("deletions", 0)),
    ])
if brief_path.exists():
    text_parts.append(brief_path.read_text())

blob = " ".join(text_parts).lower()

scores = {"focus": 0, "energy": 0, "flow": 0}

focus_kw = ["architecture", "security", "auth", "migration", "schema", "api", "infra", "boundary", "service", "contract"]
energy_kw = ["breaking", "major", "release", "critical", "performance", "refactor", "large"]
flow_kw = ["collaboration", "team", "review", "docs", "onboarding", "workflow", "ownership", "process", "skill", "playbook"]

for w in focus_kw:
    if w in blob:
        scores["focus"] += 2
for w in energy_kw:
    if w in blob:
        scores["energy"] += 2
for w in flow_kw:
    if w in blob:
        scores["flow"] += 2

additions = 0
deletions = 0
if context_path.exists():
    ctx = json.loads(context_path.read_text())
    additions = int(ctx.get("additions") or 0)
    deletions = int(ctx.get("deletions") or 0)

if additions + deletions > 600:
    scores["energy"] += 3
elif additions + deletions > 200:
    scores["energy"] += 1

if "collaboration" in blob or "team" in blob:
    scores["flow"] += 2

track = max(scores, key=scores.get)
if scores[track] == 0:
    track = "flow"

reasons = []
if track == "focus":
    reasons.append("Architecture, security, or system-boundary signals dominated.")
elif track == "energy":
    reasons.append("Large or high-impact change signals dominated.")
else:
    reasons.append("Collaboration, process, or onboarding signals dominated.")

reason = " ".join(reasons) + f" Scores: focus={scores['focus']}, energy={scores['energy']}, flow={scores['flow']}."

files = {"focus": "bgm-focus.mp3", "energy": "bgm-energy.mp3", "flow": "bgm-flow.mp3"}

out = {
    "track": track,
    "file": files[track],
    "label": track.capitalize(),
    "reason": reason,
    "scores": scores,
}

out_json.write_text(json.dumps(out, indent=2))
selection_ts.write_text(
    f'''/** Auto-generated by scripts/select_bgm.sh — do not edit by hand */
export const selectedBgm = "{track}" as const;
export type BgmTrack = typeof selectedBgm;
export const bgmFile = "{files[track]}";
export const bgmSelectionReason = {json.dumps(reason)};
'''
)
print(f"Selected BGM: {track} ({files[track]})")
print(reason)
PY
